apiVersion: batch/v1
kind: Job
metadata:
  name: ffmpeg-stream-forward
spec:
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: ffmpeg
        image: "ossrs/oryx:v5.15.20"
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |-
          # config oryx host name and the secret to push stream
          # TODO: modify service ip before applying test
          oryx_host="34.168.64.155"
          # TODO: modify secret before applying test
          secret="3d633fa9f64e4f3fb2b2b02df4b73a6c"
          # config the number of streams to generate
          streams_count=40
          # config the already exist streams, the stream id.
          apps=(
            "live/naturalworldai"
          )
          apps_count=${#apps[@]}
          echo "app count is ${apps_count}"
          for ((i=1;i<=${streams_count};i++));
          do
          r=`shuf -i 1-${apps_count} -n 1`
          # echo "r = ${r}"
          echo "cp rtmp://${oryx_host}/${apps[r-1]} to live/test${i}"
          ffmpeg -nostdin -loglevel quiet -i rtmp://${oryx_host}/${apps[r-1]} -c copy -f flv rtmp://${oryx_host}/live/test${i}?secret=${secret} &
          done
          while true; do
            sleep 1
            if [[ $(ps aux |grep ffmpeg |grep -v grep |grep -v usr |grep -q ffmpeg || echo no) == no ]]; then
              echo "all ffmpeg process done"
              break
            fi
          done
          echo "complete ffmpeg job"
      restartPolicy: Never