apiVersion: v1
kind: Service
metadata:
  name: {{ include "srs.fullname" . }}
  labels:
    {{- include "srs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rtmp
      port: {{ .Values.service.rtmp }}
      targetPort: 1935
      protocol: TCP
  selector:
    {{- include "srs.selectorLabels" . | nindent 4 }}
